import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, ChevronRight, ChevronLeft, Check, ChefHat, Clock, Users, Activity, Printer } from 'lucide-react';
import { Recipe } from '../types';

interface KitchenModeProps {
  recipe: Recipe;
  onClose: () => void;
}

const escapeHtml = (s: unknown): string =>
  String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#x27;');

export function KitchenMode({ recipe, onClose }: KitchenModeProps) {
  const [currentStep, setCurrentStep] = useState(0);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);

  const totalSteps = recipe.instructions.length;
  const progress = ((currentStep + 1) / totalSteps) * 100;

  const printRecipe = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert("Please allow popups to print your recipe.");
      return;
    }

    printWindow.document.write(`
      <html>
        <head>
          <title>${escapeHtml(recipe.title)} - Kitchen Instructions</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Playfair+Display:wght@700&display=swap');
            body { 
              font-family: 'Inter', sans-serif; 
              padding: 40px; 
              color: #1a1a1a; 
              line-height: 1.6; 
              max-width: 800px; 
              margin: 0 auto; 
            }
            h1 { 
              color: #8B4513; 
              font-family: 'Playfair Display', serif; 
              border-bottom: 4px solid #DAA520; 
              padding-bottom: 10px; 
              margin-bottom: 20px; 
              text-align: center; 
            }
            .meta { text-align: center; color: #666; margin-bottom: 30px; font-size: 0.9em; }
            h2 { color: #DAA520; margin-top: 30px; border-bottom: 1px solid #eee; font-family: 'Playfair Display', serif; }
            ul, ol { margin-top: 15px; }
            li { margin-bottom: 10px; }
            .footer { margin-top: 40px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; text-align: center; }
            @media print { .footer { position: fixed; bottom: 0; } }
          </style>
        </head>
        <body>
          <h1>${escapeHtml(recipe.title)}</h1>
          <div class="meta">Time: ${escapeHtml(recipe.time)} | Yield: ${escapeHtml(recipe.servings)} Guests</div>
          <p><em>${escapeHtml(recipe.description)}</em></p>

          <h2>Ingredients</h2>
          <ul>
            ${recipe.ingredients.map(ing => `<li>${escapeHtml(ing)}</li>`).join('')}
          </ul>

          <h2>Method</h2>
          <ol>
            ${recipe.instructions.map(step => `<li>${escapeHtml(step)}</li>`).join('')}
          </ol>
          
          <div class="footer">Generated by Thaal Traditions Orchestrator • Copyright Ali Asger Talib / Noore Sara A Talib</div>
          <script>
            window.onload = function() {
              window.print();
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const toggleStepCompleted = (index: number) => {
    setCompletedSteps(prev => 
      prev.includes(index) ? prev.filter(i => i !== index) : [...prev, index]
    );
  };

  const nextStep = () => {
    if (currentStep < totalSteps - 1) {
      setCurrentStep(prev => prev + 1);
    }
  };

  const prevStep = () => {
    if (currentStep > 0) {
      setCurrentStep(prev => prev - 1);
    }
  };

  return (
    <div className="fixed inset-0 bg-black z-[500] flex flex-col font-sans overflow-hidden">
      {/* Heavy Contrast Header */}
      <header className="bg-zinc-900 p-8 md:p-12 border-b-4 border-brand-gold flex items-center justify-between">
        <div className="flex items-center gap-10">
          <button 
            onClick={onClose}
            className="w-20 h-20 bg-brand-gold text-brand-bg flex items-center justify-center rounded-full hover:scale-105 active:scale-95 transition-all shadow-2xl"
            title="Exit Kitchen Mode"
          >
            <X className="w-10 h-10" />
          </button>
          <div>
            <h2 className="text-brand-gold uppercase text-xs tracking-mega font-black mb-2 opacity-80">Mission Critical Command</h2>
            <h3 className="text-3xl md:text-5xl font-serif text-white font-bold leading-tight">{recipe.title}</h3>
          </div>
        </div>

        <div className="flex items-center gap-6">
          <button 
            onClick={printRecipe}
            className="flex items-center gap-3 px-6 py-3 bg-white/5 border border-white/10 rounded-full text-white/60 hover:bg-white hover:text-black transition-all text-xs font-bold uppercase tracking-widest"
          >
            <Printer className="w-4 h-4" /> Print Instructions
          </button>
          <div className="hidden lg:flex items-center gap-12 py-4 px-10 bg-black/40 rounded-3xl border border-white/10">
            <div className="flex flex-col items-center">
              <span className="text-[10px] uppercase font-black text-brand-gold mb-1">Time Command</span>
              <span className="text-2xl font-mono text-white">{recipe.time}</span>
            </div>
            <div className="w-px h-10 bg-white/10" />
            <div className="flex flex-col items-center">
              <span className="text-[10px] uppercase font-black text-brand-gold mb-1">Thaal Density</span>
              <span className="text-2xl font-mono text-white">{recipe.servings} Guests</span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Orchestration Area */}
      <div className="flex-1 flex overflow-hidden">
        {/* Vertical Step Progressor (Master's Logic) */}
        <aside className="w-80 bg-zinc-900/50 border-r-4 border-brand-gold/30 overflow-y-auto no-scrollbar hidden md:block">
           <div className="p-8 space-y-4">
              <h4 className="text-[10px] uppercase font-black text-brand-gold mb-8 tracking-widest text-center border-b border-brand-gold/20 pb-4">Culinary Timeline</h4>
              {recipe.instructions.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setCurrentStep(i)}
                  className={`w-full p-6 rounded-2xl flex items-center gap-6 transition-all border-2 ${
                    currentStep === i 
                    ? 'bg-brand-gold border-brand-gold text-brand-bg scale-105 shadow-xl' 
                    : completedSteps.includes(i)
                    ? 'bg-green-600 border-green-500 text-black'
                    : 'bg-black/40 border-white/5 text-white/40 hover:border-brand-gold/50'
                  }`}
                >
                  <span className="text-2xl font-black font-mono">{String(i + 1).padStart(2, '0')}</span>
                  {completedSteps.includes(i) && <Check className="w-6 h-6 ml-auto" />}
                </button>
              ))}
           </div>
        </aside>

        {/* Dynamic Instruction Zone */}
        <main className="flex-1 overflow-y-auto p-12 md:p-24 flex flex-col items-center justify-center bg-black">
          <AnimatePresence mode="wait">
            <motion.div
              key={currentStep}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 1.05 }}
              className="max-w-5xl w-full space-y-12"
            >
              <div className="inline-block px-8 py-3 bg-brand-gold/10 border-2 border-brand-gold text-brand-gold rounded-full text-sm font-black uppercase tracking-mega mb-8">
                Execution Stage 0{currentStep + 1}
              </div>
              
              <h1 className="text-5xl md:text-8xl font-serif text-white font-bold leading-[1.1] text-balance">
                {recipe.instructions[currentStep]}
              </h1>

              <div className="pt-16 flex flex-wrap gap-8">
                <button 
                  onClick={() => toggleStepCompleted(currentStep)}
                  className={`flex items-center gap-6 px-16 py-10 rounded-[2.5rem] border-4 transition-all scale-100 hover:scale-105 active:scale-95 ${
                    completedSteps.includes(currentStep)
                    ? 'bg-green-600 border-green-400 text-black'
                    : 'bg-black border-white text-white hover:border-brand-gold hover:text-brand-gold'
                  }`}
                >
                  {completedSteps.includes(currentStep) ? (
                    <>
                      <Check className="w-12 h-12" />
                      <span className="uppercase text-xl font-black tracking-widest">Ritual Verified</span>
                    </>
                  ) : (
                    <>
                      <div className="w-12 h-12 rounded-full border-4 border-current" />
                      <span className="uppercase text-xl font-black tracking-widest">Execute Ritual</span>
                    </>
                  )}
                </button>

                <div className="flex-1 bg-zinc-900 border-2 border-white/10 rounded-[2.5rem] p-10 flex items-center gap-8">
                   <div className="w-16 h-16 rounded-2xl bg-brand-gold/10 flex items-center justify-center text-brand-gold">
                      <ChefHat className="w-10 h-10" />
                   </div>
                   <div className="flex-1">
                      <span className="text-[10px] uppercase font-black text-brand-gold tracking-widest block mb-2">Technique Guidance</span>
                      <p className="text-lg text-white/50 leading-relaxed font-light italic">
                        Follow the sequence. Precision in timing is the difference between a meal and a dawat.
                      </p>
                   </div>
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </main>
      </div>

      {/* Pinned Zubaan-ni-Chatas (Universal Condiment Access) */}
      <div className="bg-zinc-900 border-t-4 border-brand-gold p-8 relative flex items-center gap-10">
        <div className="flex items-center gap-4 shrink-0">
          <Activity className="w-6 h-6 text-brand-gold animate-pulse" />
          <span className="text-xs uppercase font-black text-brand-gold tracking-widest">Zubaan-ni-Chatas PINNED</span>
        </div>
        <div className="flex gap-4 overflow-x-auto no-scrollbar pb-2">
           {['Gol-nu-Achar', 'Lasan-ni-Chutney', 'Kachumber'].map((item, i) => (
             <div key={i} className="px-8 py-4 bg-brand-gold/10 border-2 border-brand-gold/40 rounded-2xl text-[11px] font-bold text-white whitespace-nowrap">
               {item} <span className="opacity-40 ml-2">ALWAYS SERVED</span>
             </div>
           ))}
        </div>
        <div className="ml-auto flex items-center gap-6">
           <button 
             onClick={prevStep}
             disabled={currentStep === 0}
             className={`w-20 h-20 rounded-full border-4 border-white/10 flex items-center justify-center text-white transition-all ${
               currentStep === 0 ? 'opacity-20 cursor-not-allowed' : 'hover:bg-white hover:text-black hover:border-white'
             }`}
           >
             <ChevronLeft className="w-10 h-10" />
           </button>
           <button 
             onClick={nextStep}
             disabled={currentStep === totalSteps - 1}
             className={`w-20 h-20 rounded-full border-4 border-white/10 flex items-center justify-center text-white transition-all ${
               currentStep === totalSteps - 1 ? 'opacity-20 cursor-not-allowed' : 'hover:bg-white hover:text-black hover:border-white'
             }`}
           >
             <ChevronRight className="w-10 h-10" />
           </button>
        </div>
      </div>
    </div>
  );
}
